"""
SVG rendering backend for the L-System Renderer.

Produces high-quality SVG output with auto-scaling, centering,
optional animation, and compact grouped paths.
"""

from __future__ import annotations

import logging
from collections import defaultdict
from typing import Dict, List, Tuple

from ..core.types import Segment
from ..utils.colors import _escape_xml

logger = logging.getLogger(__name__)


class SVGRenderer:
    """Renders segments to an SVG file.

    Supports:
      - Auto-scaling and centering
      - Configurable background, margins
      - Optional SVG animation (progressive draw)
      - Title and metadata
      - Compact grouped paths for smaller file size
    """

    def __init__(
        self,
        width: int = 800,
        height: int = 800,
        background: str = "#ffffff",
        margin: float = 20.0,
        title: str = "",
    ):
        self.width = width
        self.height = height
        self.background = background
        self.margin = margin
        self.title = title

    def _compute_bounds(self, segments: List[Segment]) -> Tuple[float, float, float, float]:
        """Compute the bounding box of all segments."""
        if not segments:
            return (0, 0, 100, 100)
        xs = []
        ys = []
        for seg in segments:
            xs.extend([seg.x1, seg.x2])
            ys.extend([seg.y1, seg.y2])
        return min(xs), min(ys), max(xs), max(ys)

    def render(
        self,
        segments: List[Segment],
        output_path: str,
        animate: bool = False,
        animation_duration: float = 5.0,
    ) -> str:
        """Render segments to an SVG file.

        Args:
            segments: List of Segment objects to render.
            output_path: Path to write the SVG file.
            animate: If True, add SVG animation that draws segments progressively.
            animation_duration: Duration of animation in seconds (if animate=True).

        Returns:
            Path to the output file.
        """
        if not segments:
            # Write empty SVG
            lines = [
                '<?xml version="1.0" encoding="UTF-8"?>',
                f'<svg xmlns="http://www.w3.org/2000/svg" '
                f'width="{self.width}" height="{self.height}" '
                f'viewBox="0 0 {self.width} {self.height}">',
                f'<rect width="{self.width}" height="{self.height}" fill="{self.background}"/>',
                '</svg>',
            ]
            with open(output_path, "w") as f:
                f.write("\n".join(lines))
            return output_path

        min_x, min_y, max_x, max_y = self._compute_bounds(segments)
        data_w = max_x - min_x or 1.0
        data_h = max_y - min_y or 1.0

        # Scale to fit within the SVG viewport with margins
        avail_w = self.width - 2 * self.margin
        avail_h = self.height - 2 * self.margin
        scale = min(avail_w / data_w, avail_h / data_h)

        # Center the drawing
        offset_x = self.margin + (avail_w - data_w * scale) / 2
        offset_y = self.margin + (avail_h - data_h * scale) / 2

        lines: List[str] = []
        lines.append('<?xml version="1.0" encoding="UTF-8"?>')
        lines.append(
            f'<svg xmlns="http://www.w3.org/2000/svg" '
            f'width="{self.width}" height="{self.height}" '
            f'viewBox="0 0 {self.width} {self.height}">'
        )
        if self.title:
            lines.append(f"<title>{_escape_xml(self.title)}</title>")
            lines.append(f"<desc>{_escape_xml('Generated by lsystem-renderer-q4m7')}</desc>")

        lines.append(
            f'<rect width="{self.width}" height="{self.height}" '
            f'fill="{self.background}"/>'
        )

        # Group segments by (color, width) for compact but accurate SVG
        if not animate:
            # Group by (color, rounded_width) to avoid float grouping issues
            style_groups: Dict[Tuple[str, float], List[Segment]] = defaultdict(list)
            for seg in segments:
                # Round width to 2 decimal places for grouping
                key = (seg.color, round(seg.width, 2))
                style_groups[key].append(seg)

            for (color, width), group in style_groups.items():
                path_parts = []
                for seg in group:
                    sx1 = (seg.x1 - min_x) * scale + offset_x
                    sy1 = self.height - ((seg.y1 - min_y) * scale + offset_y)
                    sx2 = (seg.x2 - min_x) * scale + offset_x
                    sy2 = self.height - ((seg.y2 - min_y) * scale + offset_y)
                    path_parts.append(f"M{sx1:.2f},{sy1:.2f} L{sx2:.2f},{sy2:.2f}")
                path_d = " ".join(path_parts)
                lines.append(
                    f'<path d="{path_d}" stroke="{color}" '
                    f'stroke-width="{width:.2f}" fill="none" '
                    f'stroke-linecap="round" stroke-linejoin="round"/>'
                )
        else:
            # Animated: each segment appears progressively
            total = len(segments)
            delay_per_seg = animation_duration / total
            for i, seg in enumerate(segments):
                sx1 = (seg.x1 - min_x) * scale + offset_x
                sy1 = self.height - ((seg.y1 - min_y) * scale + offset_y)
                sx2 = (seg.x2 - min_x) * scale + offset_x
                sy2 = self.height - ((seg.y2 - min_y) * scale + offset_y)
                begin = f"{i * delay_per_seg:.3f}s"
                dur = f"{delay_per_seg * 3:.3f}s"
                lines.append(
                    f'<line x1="{sx1:.3f}" y1="{sy1:.3f}" '
                    f'x2="{sx2:.3f}" y2="{sy2:.3f}" '
                    f'stroke="{seg.color}" stroke-width="{seg.width:.2f}" '
                    f'stroke-linecap="round" opacity="0">'
                    f'<animate attributeName="opacity" from="0" to="1" '
                    f'begin="{begin}" dur="{dur}" fill="freeze"/>'
                    f'</line>'
                )

        lines.append("</svg>")

        with open(output_path, "w") as f:
            f.write("\n".join(lines))

        logger.info("Rendered %d segments to %s", len(segments), output_path)
        return output_path