"""
Built-in preset L-system definitions.

Contains classic fractals, plant models, space-filling curves, and more.
"""

from __future__ import annotations

from .types import LSystemDefinition, LSystemRule

PRESETS: dict[str, LSystemDefinition] = {
    # ── Classic Fractals ─────────────────────────────────────────────
    "koch_curve": LSystemDefinition(
        name="Koch Curve",
        axiom="F",
        rules=[LSystemRule("F", "F+F--F+F")],
        angle=60.0,
        step_size=3.0,
        iterations=4,
        line_width=1.0,
    ),
    "koch_snowflake": LSystemDefinition(
        name="Koch Snowflake",
        axiom="F--F--F",
        rules=[LSystemRule("F", "F+F--F+F")],
        angle=60.0,
        step_size=3.0,
        iterations=4,
        line_width=1.0,
    ),
    "sierpinski_triangle": LSystemDefinition(
        name="Sierpiński Triangle",
        axiom="F-G-G",
        rules=[
            LSystemRule("F", "F-G+F+G-F"),
            LSystemRule("G", "GG"),
        ],
        angle=120.0,
        step_size=3.0,
        iterations=6,
        line_width=1.0,
    ),
    "dragon_curve": LSystemDefinition(
        name="Dragon Curve",
        axiom="F",
        rules=[
            LSystemRule("F", "F+G"),
            LSystemRule("G", "F-G"),
        ],
        angle=90.0,
        step_size=5.0,
        iterations=12,
        line_width=1.0,
        color_mode="segment_index",
    ),
    "hilbert_curve": LSystemDefinition(
        name="Hilbert Curve",
        axiom="A",
        rules=[
            LSystemRule("A", "-BF+AFA+FB-"),
            LSystemRule("B", "+AF-BFB-FA+"),
        ],
        angle=90.0,
        step_size=5.0,
        iterations=5,
        line_width=1.0,
        color_mode="segment_index",
    ),
    "levy_c_curve": LSystemDefinition(
        name="Lévy C Curve",
        axiom="F",
        rules=[LSystemRule("F", "+F--F+")],
        angle=45.0,
        step_size=3.0,
        iterations=14,
        line_width=1.0,
        color_mode="segment_index",
    ),
    "gosper_curve": LSystemDefinition(
        name="Gosper Curve (Flowsnake)",
        axiom="A",
        rules=[
            LSystemRule("A", "A-B--B+A++AA+B-"),
            LSystemRule("B", "+A-BB--B-A++A+B"),
        ],
        angle=60.0,
        step_size=4.0,
        iterations=4,
        line_width=1.0,
        color_mode="segment_index",
    ),
    "sierpinski_arrowhead": LSystemDefinition(
        name="Sierpiński Arrowhead",
        axiom="A",
        rules=[
            LSystemRule("A", "B-A-B"),
            LSystemRule("B", "A+B+A"),
        ],
        angle=60.0,
        step_size=5.0,
        iterations=7,
        line_width=1.0,
        color_mode="segment_index",
    ),
    "peano_curve": LSystemDefinition(
        name="Peano Curve",
        axiom="X",
        rules=[
            LSystemRule("X", "XFYFX+F+YFXFY-F-XFYFX"),
            LSystemRule("Y", "YFXFY-F-XFYFX+F+YFXFY"),
        ],
        angle=90.0,
        step_size=4.0,
        iterations=3,
        line_width=1.0,
        color_mode="segment_index",
    ),
    "quadratic_koch": LSystemDefinition(
        name="Quadratic Koch Island",
        axiom="F+F+F+F",
        rules=[LSystemRule("F", "F+F-F-FF+F+F-F")],
        angle=90.0,
        step_size=3.0,
        iterations=3,
        line_width=1.0,
        color_mode="segment_index",
    ),
    # ── New: Fibonacci Word ───────────────────────────────────────────
    "fibonacci_word": LSystemDefinition(
        name="Fibonacci Word Fractal",
        axiom="0",
        rules=[
            LSystemRule("0", "01"),
            LSystemRule("1", "0"),
        ],
        angle=90.0,
        step_size=5.0,
        iterations=14,
        line_width=1.0,
        color_mode="segment_index",
    ),
    # ── New: Minkowski Sausage ────────────────────────────────────────
    "minkowski_sausage": LSystemDefinition(
        name="Minkowski Sausage",
        axiom="F",
        rules=[LSystemRule("F", "F+F-F-FF+F+F-F")],
        angle=90.0,
        step_size=3.0,
        iterations=3,
        line_width=1.0,
        color_mode="segment_index",
    ),
    # ── New: Moore Curve ──────────────────────────────────────────────
    "moore_curve": LSystemDefinition(
        name="Moore Curve",
        axiom="LFL+F+LFL",
        rules=[
            LSystemRule("L", "-RF+LFL+FR-"),
            LSystemRule("R", "+LF-RFR-FL+"),
        ],
        angle=90.0,
        step_size=5.0,
        iterations=4,
        line_width=1.0,
        color_mode="segment_index",
    ),
    # ── New: Koch Antisnowflake ──────────────────────────────────────
    "koch_antisnowflake": LSystemDefinition(
        name="Koch Antisnowflake",
        axiom="F--F--F",
        rules=[LSystemRule("F", "F+F--F+F")],
        angle=60.0,
        step_size=3.0,
        iterations=4,
        line_width=1.0,
        color_mode="position",
        gradient=("#1a73e8", "#e8451a"),
    ),
    # ── New: Cesaro Fractal ──────────────────────────────────────────
    "cesaro_fractal": LSystemDefinition(
        name="Cesàro Fractal",
        axiom="F",
        rules=[LSystemRule("F", "F+F--F+F")],
        angle=80.0,
        step_size=4.0,
        iterations=5,
        line_width=1.0,
        color_mode="segment_index",
    ),
    # ── Plant Models ─────────────────────────────────────────────────
    "plant_simple": LSystemDefinition(
        name="Simple Plant",
        axiom="F",
        rules=[LSystemRule("F", "F[+F]F[-F]F")],
        angle=25.7,
        step_size=4.0,
        iterations=5,
        line_width=1.0,
        colors={
            0: "#5a3e1b",
            1: "#3d6b2e",
            2: "#4a8c3a",
            3: "#6bb55a",
            4: "#8dd77a",
            5: "#a8f08a",
        },
    ),
    "plant_stochastic": LSystemDefinition(
        name="Stochastic Plant",
        axiom="F",
        rules=[
            LSystemRule("F", "F[+F]F[-F]F", probability=0.5),
            LSystemRule("F", "F[+F]F", probability=0.25),
            LSystemRule("F", "F[-F]F", probability=0.25),
        ],
        angle=25.7,
        step_size=4.0,
        iterations=5,
        line_width=1.5,
        colors={
            0: "#5a3e1b",
            1: "#3d6b2e",
            2: "#4a8c3a",
            3: "#6bb55a",
            4: "#8dd77a",
            5: "#a8f08a",
        },
    ),
    "tree_bushy": LSystemDefinition(
        name="Bushy Tree",
        axiom="F",
        rules=[LSystemRule("F", "FF+[+F-F-F]-[-F+F+F]")],
        angle=22.5,
        step_size=4.0,
        iterations=4,
        line_width=1.5,
        colors={
            0: "#4a2f0a",
            1: "#5a3e1b",
            2: "#3d6b2e",
            3: "#5a9e3a",
            4: "#7abf5a",
            5: "#a8f08a",
        },
    ),
    "tree_willow": LSystemDefinition(
        name="Willow Tree",
        axiom="F",
        rules=[LSystemRule("F", "FF+[+F-F-F]-[-F+F+F]")],
        angle=25.0,
        step_size=5.0,
        iterations=5,
        line_width=1.5,
        perturbation=2.0,
        colors={
            0: "#5a3e1b",
            1: "#4a5e2e",
            2: "#3d7c3a",
            3: "#5a9e5a",
            4: "#7abf6a",
            5: "#9adf8a",
        },
    ),
    "fractal_tree": LSystemDefinition(
        name="Fractal Tree",
        axiom="X",
        rules=[
            LSystemRule("X", "F+[[X]-X]-F[-FX]+X"),
            LSystemRule("F", "FF"),
        ],
        angle=25.0,
        step_size=4.0,
        iterations=6,
        line_width=1.5,
        colors={
            0: "#5a3e1b",
            1: "#4a6e2e",
            2: "#3d8c3a",
            3: "#5aae5a",
            4: "#7acf6a",
            5: "#9aef8a",
            6: "#baffaa",
        },
    ),
    "barnsley_fern": LSystemDefinition(
        name="Barnsley Fern (approximation)",
        axiom="X",
        rules=[
            LSystemRule("X", "F+[[X]-X]-F[-FX]+X"),
            LSystemRule("F", "FF"),
        ],
        angle=25.0,
        step_size=3.0,
        iterations=5,
        line_width=1.0,
        colors={
            0: "#1a5c1a",
            1: "#228b22",
            2: "#32cd32",
            3: "#7cfc00",
            4: "#adff2f",
        },
    ),
    # ── New: Bushy Plant (Alternate) ─────────────────────────────────
    "plant_alternate": LSystemDefinition(
        name="Alternate Branching Plant",
        axiom="F",
        rules=[LSystemRule("F", "F[+F]F[-F][F]")],
        angle=20.0,
        step_size=5.0,
        iterations=5,
        line_width=1.2,
        colors={
            0: "#6b3a2a",
            1: "#3d8b2e",
            2: "#5aac3a",
            3: "#7acd5a",
            4: "#9aee7a",
            5: "#c0ffa0",
        },
    ),
    # ── Space-Filling & Special ──────────────────────────────────────
    "penrose_tiles": LSystemDefinition(
        name="Penrose Tiles",
        axiom="[7]++[7]++[7]++[7]++[7]",
        rules=[
            LSystemRule("6", "81++91----71[-81----61]++"),
            LSystemRule("7", "+81--91[---61--71]"),
            LSystemRule("8", "-61++71[+++81++91]-"),
            LSystemRule("9", "--81+++61[+91+++71]--71"),
        ],
        angle=36.0,
        step_size=4.0,
        iterations=4,
        line_width=0.8,
    ),
    "cantor_dust": LSystemDefinition(
        name="Cantor Dust",
        axiom="F",
        rules=[
            LSystemRule("F", "FfF"),
            LSystemRule("f", "fff"),
        ],
        angle=0.0,
        step_size=5.0,
        iterations=4,
        line_width=2.0,
        color_mode="single",
    ),
}